### ISSUE TITLE
Inconsistent Licensing Information

### ISSUE THREAD

**Issue by radj307** [linuxgurugamer/ksp_toolbar#30]
I was digging through the source code for this to learn a bit about modding KSP's UI, and came across a small inconsistency that you may want to clear up.

In `Toolbar/Internal/Utils.cs`:`63`:
```cs
// The following function was initially copied from @JPLRepo's AmpYear mod, which is covered by the GPL, as is this mod
```

This mod isn't licensed under the GPL, it's licensed under [BSD-2](https://github.com/linuxgurugamer/ksp_toolbar/blob/master/LICENSE.txt).

Since the differences between the original function and this implementation of the function are relatively minor, that is a [violation](https://opensource.stackexchange.com/questions/35/if-i-include-some-gpl-code-in-my-project-can-i-release-it-as-bsd) of the [GPLv3](https://github.com/JPLRepo/AmpYear/blob/master/Distribution/GameData/REPOSoftTech/AmpYear/LICENSE) license used by AmpYear. You should rewrite the function from scratch & delete the comment referencing this project as being licensed under the GPL.  

anal asf, I know; but I figured you would want to know about it sooner rather than later.

**Comment by linuxgurugamer** [comment]
Well, thank you so much for creating some extra work for me.  It's not as if I don't have anything else to do.
I'll have to pull it out and put it into it's own dll, I'm sure everyone who sees this will thank you for slowing KSP down just a little bit more.

If you feel so strongly about this, maybe you could, instead of pointing out a relatively harmless issue, maybe fix it yourself by rewriting the function in question?

I won't be able to get to this for a while, so if you do, I would appreciate the PR

**Comment by radj307** [comment]
I don't feel strongly about it, but I'm working on a PR right now anyway; I would like to remind you that I didn't 'create' any extra work here, I just pointed out an inconsistency that I saw.

Edit: [It's submitted](https://github.com/linuxgurugamer/ksp_toolbar/pull/31)
